export const SET_WALLET_STATE = 'SET_WALLET_STATE';

export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';

export const OPEN_WALLET_DIALOG = 'OPEN_WALLET_DIALOG';

export const STORE_GUILD_REQUIREMENT = 'STORE_GUILD_REQUIREMENT';


