export const SET_ALL_GUILDS = 'SET_ALL_GUILDS';

export const SET_CHALLENGE = 'SET_CHALLENGE';

export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';

export const SET_WALLET_STATE = 'SET_WALLET_STATE';

export const STORE_GUILD_REQUIREMENT = 'STORE_GUILD_REQUIREMENT';


